- name: using handlers
  hosts: all
  become: yes
  tasks:
    - name: install the package
      yum:
        name: httpd
        state: latest
      notify:
        - hand1

    - name: print hi
      debug:
        msg: "hello there"
      changed_when: true
      notify:
        - hand1

  handlers:
    - name: hand1
      service:
        name: httpd
        state: started
        enabled: yes
