---
environment_name: Dev1

informatica_root_directory: "/opt/informatica961"

# defaults file for informatica
informatica:
  owner: ifadmin
  group: ifadmin
  users:
  - user: ifadmin
    group: ifadmin
  - user: ifuser
    group: ifuser

  db:
    type: Oracle # Oracle/MSSQLServer/DB2/Sybase
    username: test
    password: test
    address: db.domain.com:1521
    servicename: servicename
  domain:
    name: "{{ environment_name }}"
    hostname: testserver
    port: 6005
    user: user
    password: password
    cnfrm_password: password
  keystore_password: Password1
  serves_as_gateway: 1
  nodename: "node1_{{ environment_name }}"
  base_directory: "{{ informatica_root_directory }}/{{ environment_name }}"
  archive: /mnt/nfs/ansible/informatica/961HF3_Server_Installer_linux-x64.tar
  oracle_client:
    archive: /mnt/nfs/ansible/informatica/linux.x64_11gR2_client.zip
    destination: /u00/app/oracle
    unarchive_directory: /home/oracle/
    hostname: rh68test1

  key_file: /mnt/nfs/ansible/informatica/my.key
  timezone: America/Los_Angeles
  silentinput_properties_file: SilentInput.properties.j2

informatica_directory: "{{ informatica.base_directory }}/sw"
informatica_install_directory: "{{ informatica.base_directory }}/install_dir"

informatica_enable_usage_collection: 1

informatica_encryption_key_directory: "{{ informatica_install_directory }}/isp/config/keys"
informatica_temp_directory: "/tmp"


informatica_user_limits:
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "core"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "core"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "data"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "data"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "fsize"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "nproc"
  value: "65000"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "nproc"
  value: "65000"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "nofile"
  value: "64000"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "nofile"
  value: "64000"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "priority"
  value: "0"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "priority"
  value: "0"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "rtprio"
  value: "0"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "rtprio"
  value: "0"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "stack"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "stack"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "cpu"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "cpu"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "sigpending"
  value: "63668"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "sigpending"
  value: "63668"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "memlock"
  value: "64"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "memlock"
  value: "64"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "as"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "as"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "msgqueue"
  value: "819200"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "msgqueue"
  value: "819200"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "locks"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "locks"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "soft"
  item: "rss"
  value: "unlimited"
- domain: "{{ informatica.owner }}"
  type: "hard"
  item: "rss"
  value: "unlimited"